# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fyreman/bachelorarbeit/BachelorProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fyreman/bachelorarbeit/BachelorProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fyreman/bachelorarbeit/BachelorProject/CMakeFiles /home/fyreman/bachelorarbeit/BachelorProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fyreman/bachelorarbeit/BachelorProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named FindAngles

# Build rule for target.
FindAngles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FindAngles
.PHONY : FindAngles

# fast build rule for target.
FindAngles/fast:
	$(MAKE) -f CMakeFiles/FindAngles.dir/build.make CMakeFiles/FindAngles.dir/build
.PHONY : FindAngles/fast

linux_src/FileWriter.o: linux_src/FileWriter.cpp.o

.PHONY : linux_src/FileWriter.o

# target to build an object file
linux_src/FileWriter.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/FileWriter.cpp.o
.PHONY : linux_src/FileWriter.cpp.o

linux_src/FileWriter.i: linux_src/FileWriter.cpp.i

.PHONY : linux_src/FileWriter.i

# target to preprocess a source file
linux_src/FileWriter.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/FileWriter.cpp.i
.PHONY : linux_src/FileWriter.cpp.i

linux_src/FileWriter.s: linux_src/FileWriter.cpp.s

.PHONY : linux_src/FileWriter.s

# target to generate assembly for a file
linux_src/FileWriter.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/FileWriter.cpp.s
.PHONY : linux_src/FileWriter.cpp.s

linux_src/FindAngles.o: linux_src/FindAngles.cpp.o

.PHONY : linux_src/FindAngles.o

# target to build an object file
linux_src/FindAngles.cpp.o:
	$(MAKE) -f CMakeFiles/FindAngles.dir/build.make CMakeFiles/FindAngles.dir/linux_src/FindAngles.cpp.o
.PHONY : linux_src/FindAngles.cpp.o

linux_src/FindAngles.i: linux_src/FindAngles.cpp.i

.PHONY : linux_src/FindAngles.i

# target to preprocess a source file
linux_src/FindAngles.cpp.i:
	$(MAKE) -f CMakeFiles/FindAngles.dir/build.make CMakeFiles/FindAngles.dir/linux_src/FindAngles.cpp.i
.PHONY : linux_src/FindAngles.cpp.i

linux_src/FindAngles.s: linux_src/FindAngles.cpp.s

.PHONY : linux_src/FindAngles.s

# target to generate assembly for a file
linux_src/FindAngles.cpp.s:
	$(MAKE) -f CMakeFiles/FindAngles.dir/build.make CMakeFiles/FindAngles.dir/linux_src/FindAngles.cpp.s
.PHONY : linux_src/FindAngles.cpp.s

linux_src/ImageProcessing.o: linux_src/ImageProcessing.cpp.o

.PHONY : linux_src/ImageProcessing.o

# target to build an object file
linux_src/ImageProcessing.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/ImageProcessing.cpp.o
.PHONY : linux_src/ImageProcessing.cpp.o

linux_src/ImageProcessing.i: linux_src/ImageProcessing.cpp.i

.PHONY : linux_src/ImageProcessing.i

# target to preprocess a source file
linux_src/ImageProcessing.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/ImageProcessing.cpp.i
.PHONY : linux_src/ImageProcessing.cpp.i

linux_src/ImageProcessing.s: linux_src/ImageProcessing.cpp.s

.PHONY : linux_src/ImageProcessing.s

# target to generate assembly for a file
linux_src/ImageProcessing.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/ImageProcessing.cpp.s
.PHONY : linux_src/ImageProcessing.cpp.s

linux_src/main.o: linux_src/main.cpp.o

.PHONY : linux_src/main.o

# target to build an object file
linux_src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/main.cpp.o
.PHONY : linux_src/main.cpp.o

linux_src/main.i: linux_src/main.cpp.i

.PHONY : linux_src/main.i

# target to preprocess a source file
linux_src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/main.cpp.i
.PHONY : linux_src/main.cpp.i

linux_src/main.s: linux_src/main.cpp.s

.PHONY : linux_src/main.s

# target to generate assembly for a file
linux_src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/linux_src/main.cpp.s
.PHONY : linux_src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Main"
	@echo "... FindAngles"
	@echo "... linux_src/FileWriter.o"
	@echo "... linux_src/FileWriter.i"
	@echo "... linux_src/FileWriter.s"
	@echo "... linux_src/FindAngles.o"
	@echo "... linux_src/FindAngles.i"
	@echo "... linux_src/FindAngles.s"
	@echo "... linux_src/ImageProcessing.o"
	@echo "... linux_src/ImageProcessing.i"
	@echo "... linux_src/ImageProcessing.s"
	@echo "... linux_src/main.o"
	@echo "... linux_src/main.i"
	@echo "... linux_src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

